spring:
  application:
    name: spring-mvc-thymeleaf-project

countries: Brazil,France,Germany,India,Mexico,Spain,Portugal
languages: Go,Java,Python,JavaScript,Rust
operatingSystems: Linux, macOS, Microsoft Windows, Android OS, iOS